
CREATE TABLE Customers (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL,
    `email` VARCHAR(50) NOT NULL,
    `location` VARCHAR(100) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME() on UPDATE CURRENT_TIMESTAMP()
);

CREATE TABLE Categories (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `customer_id` BIGINT(20) UNSIGNED NOT NULL,
    `category_name` VARCHAR(50) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME() on UPDATE CURRENT_TIMESTAMP(),
     FOREIGN KEY (`customer_id`) REFERENCES `Customers` (`id`) on DELETE RESTRICT on UPDATE CASCADE
);

CREATE TABLE Products (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `category_id` BIGINT(20) UNSIGNED NOT NULL,
    `name` VARCHAR(50) NOT NULL,
    `description` VARCHAR(50) NOT NULL,
    `price` DECIMAL(10, 2),
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME() on UPDATE CURRENT_TIMESTAMP(),
     FOREIGN KEY (`category_id`) REFERENCES `Categories` (`id`) on DELETE RESTRICT on UPDATE CASCADE
);

CREATE TABLE Orders (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `customer_id` BIGINT(20) UNSIGNED NOT NULL,
    `order_date` DATE,
    `total_amount` DECIMAL(10, 2),
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME() on UPDATE CURRENT_TIMESTAMP(),
    FOREIGN KEY (customer_id) REFERENCES Customers(`id`) on DELETE RESTRICT on UPDATE CASCADE

);

CREATE TABLE OrderItems (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `order_id` BIGINT(20) UNSIGNED NOT NULL,
    `product_id` BIGINT(20) UNSIGNED NOT NULL,
    `quantity` BIGINT(20) UNSIGNED NOT NULL,
    `unit_price` DECIMAL(10, 2),
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME(),
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIME() on UPDATE CURRENT_TIMESTAMP(),
    FOREIGN KEY (order_id) REFERENCES Orders(`id`) on DELETE RESTRICT on UPDATE CASCADE,
    FOREIGN KEY (product_id) REFERENCES Products(`id`) on DELETE RESTRICT on UPDATE CASCADE
);